default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: carmelo_development
  username: carmelo
  password: carmelo_pass

test:
  <<: *default
  database: carmelo_test

production:
  <<: *default
  database: carmelo_production
  username: <%= ENV['AUTOYMATE_DATABASE_USER'] %>
  password: <%= ENV['AUTOYMATE_DATABASE_PASSWORD'] %>
