# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6e5ae744ce7a91c2a626baf5dd69bf8adb5abca16ccfb87b8a4b95a1abbacaac57dd68d2991c21e99d79ef76025e5fdc5030a272a8b85a5ee2a571814e1a45

test:
  secret_key_base: bf7d3f1b309a273eb295151d5385551c7ceca0b916e1796071549e33b21af3b4753092116833e7e87533b3e7a1ab582b930c5136c9839d48ee71e9033bfa4210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
